version: "3"
services:
  keyvaluestore_proxy:
    build: 
      context: ./web
      dockerfile: web.Dockerfile
    hostname: keyvaluestore_proxy
    ports:
      - 5000:80
    restart: always
    depends_on:
      - keyvaluestore_php
    links:
      - keyvaluestore_php
  
  keyvaluestore_php:
    build: 
      context: ./web
      dockerfile: prod.Dockerfile
      args: 
        - WITH_XDEBUG=false
    hostname: keyvaluestore_php
    restart: always
    environment: 
      - APP_URL=127.0.0.1:5000
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_HOST=keyvaluestore_db
      - DB_DATABASE=KeyValueStore
      - DB_USERNAME=admin
      - DB_PASSWORD=abc@123
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - redis
      - keyvaluestore_db

  #MySQL
  keyvaluestore_db:
    image: mariadb
    volumes:
      - "./database/prod:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abc@123
      - MYSQL_DATABASE=KeyValueStore
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=abc@123

  keyvaluestore_dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    hostname: keyvaluestore_dbadmin
    depends_on:
      - keyvaluestore_db
    ports:
      - 5001:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=keyvaluestore_db

  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379
    restart: always

networks: 
  keyvaluestore_prod:
    driver: bridge
